services:
  db:
    image: postgres:18
    container_name: konnected-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: Konnected
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Konnected"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: konnected-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


